# Generated by Django 5.0 on 2026-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='full_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='pending_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/pending/'),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='organization_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='pending_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/pending/'),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/temp/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/users/'),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
