# Generated by Django 5.0 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0002_campaign_campaign_image_donorprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='unknown', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
