# Generated by Django 5.0 on 2026-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0004_alter_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/campaigns/'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='pending_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/pending/'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='images/donor_docs/'),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='pending_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/pending/'),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='images/ngo_docs/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/temp/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='verification_document',
            field=models.FileField(upload_to='images/verification_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/users/'),
        ),
    ]
