# Generated by Django 5.0 on 2026-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0005_alter_campaign_campaign_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='pending_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='pending_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
    ]
