# Generated by Django 5.0 on 2026-02-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0006_alter_donorprofile_pending_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
    ]
