# Generated by Django 5.0 on 2026-02-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0007_remove_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='approved_at',
        ),
    ]
