# Generated by Django 5.0 on 2026-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0008_remove_register_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='pending_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='pending_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
