# Generated by Django 5.0 on 2026-02-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0010_feedback_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='pending_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='pending_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
