# Generated by Django 5.0 on 2026-02-22 02:04

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0011_donorprofile_pending_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='changes_requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='changes_requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
