# Generated by Django 5.0 on 2026-02-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0012_donorprofile_changes_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='pending_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=15),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='pending_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=15),
        ),
    ]
