# Generated by Django 5.0 on 2026-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0013_alter_donorprofile_pending_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('MEDICAL', 'Medical Supplies'), ('EDUCATION', 'Educational Materials'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
