# Generated by Django 5.0 on 2026-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0014_alter_campaign_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='campaign_title',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
