# Generated by Django 5.0 on 2026-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0015_donation_campaign_title_donation_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='ngo_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
