# Generated by Django 5.0 on 2026-03-04 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0016_donation_ngo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
