# Generated by Django 5.0 on 2026-03-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0017_donation_requested_at_alter_donation_delivered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='delivered_at',
            new_name='updated_at',
        ),
    ]
