# Generated by Django 5.0 on 2026-03-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0018_rename_delivered_at_donation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='item_type',
            field=models.CharField(default='Healthy Foods', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='unit',
            field=models.CharField(default='Sets', max_length=50),
            preserve_default=False,
        ),
    ]
