# Generated by Django 5.0 on 2026-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0022_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
