# Generated by Django 5.0 on 2026-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0024_pendingcampaign_pendingtestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcampaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcampaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
