# Generated by Django 5.0 on 2026-03-13 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0025_alter_pendingcampaign_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='changes_requested_at',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pending_address',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pending_email',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pending_image',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pending_name',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pending_phone',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pending_status',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='pending_username',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='changes_requested_at',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='pending_address',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='pending_email',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='pending_image',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='pending_name',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='pending_phone',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='pending_status',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='pending_username',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.CreateModel(
            name='PendingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profiles/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
