# Generated by Django 5.0 on 2026-03-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0026_remove_donorprofile_changes_requested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingprofile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
