# Generated by Django 5.0 on 2026-03-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0028_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
