# Generated by Django 5.0 on 2026-03-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0029_remove_feedback_status_remove_notification_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
